apiVersion: v1
kind: Pod
metadata:
 name: mukeshpodenv1
 labels:
  adhoc: mukeshenv

spec:
 containers:
  - name: mukeshcc111
    image: mkmahto7/webapp:latest
    ports:
     - containerPort: 80
    env:   
     - name: color 
       value: yellow  

